using TaskManager.Business.Abstraction.Interfaces.Mediator;

namespace TaskManager.Business.Features.AssignmentEmployeeFeatures.Commands;

public record CreateAssignmentEmployeeCommand(CreateAssignmentEmployeeRequest command) : IRequest<CreateAssignmentEmployeeResponse>;