using TaskManager.Business.Abstraction.Interfaces.Mediator;

namespace TaskManager.Business.Features.AssignmentEmployeeFeatures.Commands;

public record DeleteAssignmentEmployeeCommand(DeleteAssignmentEmployeeRequest command) : IRequest<DeleteAssignmentEmployeeResponse>;